name: develop_jn_environment
on:
  push:
    paths:
      - 'general_dev/**'
  pull_request:
    paths:
      - 'general_dev/**'
  workflow_dispatch:
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker image build
      run: |
        docker build -f general_dev/Dockerfile  -t newbuild general_dev
    - name: environment test
      run: |
        docker run --rm -v `pwd`:`pwd` -w `pwd` newbuild  bash -c "Rscript --help"

    - name: docker hub login
      run: |
        echo "${{ secrets.dockerhub_token }}" | docker login  -u ${{ secrets.dockerhub_user }} --password-stdin
    - name: Push image
      run: |
        IMAGE_ID=btrspg/jnb:general_dev
        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag newbuild $IMAGE_ID-$VERSION
        docker push $IMAGE_ID-$VERSION


